export { default as MainSlider } from './main-slider/index'
export { default as Teaser } from './teaser/index'
export { default as TopMain } from './main-top/index'
export { default as MainSeo } from './main-seo/index'
export { default as MainCompilation } from './main-compilation/index'