export { default as MainPage } from './main'
export { default as MoviesPage } from './movies'
export { default as MoviePage } from './movie'
export { default as PersonPage } from './person'
export { default as AdminPage } from './admin'
export { default as ErrorPage } from './error'
export { default as AuthPage } from './auth'